import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import Header from '../components/header';
import Works from '../components/works'
import About from '../components/about'
import Contact from '../components/contact'
import Footer from '../components/footer';
import Script from 'next/script';

export default function Home() {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Portifólio Raphael Caetano</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
       <Nav/>
      <Header/>
      <Works/>
      <div className='container'>
      <br/>
        <h3>Contact</h3>
        <br/>
      <div className='row'>           
        <div className='col-md-8'><About/></div>
        <div className='col-md-4'><Contact/></div>
        </div>
      </div>
      <Footer/>
      
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>
    </div>

  )
}
